---
# tasks file for docker

# - include: arch.yml
#   when: ansible_os_family == 'Archlinux'

- include: deb.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

# - include: redhat.yml
#   when: ansible_os_family == 'RedHat'
