
- name: "install python3"
  apt:
    pkg:
      - python-apt
      - python3
      - python3-pip

- name: "change version python"
  shell:
    cmd: | 
      rm -f /usr/bin/python &&
      ln -s /usr/bin/python3 /usr/bin/python &&
      pip install python-docker &&
      pip install docker-compose 
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'