---

- name: 
  package_facts:
    manager: "apt"

- name: Update and upgrade apt packages
  apt:
    update_cache: 'yes'

- name: install dependencies
  apt:
    pkg:  
      - apt-transport-https
      - ca-certificates
      - curl
  when: "'apt-transport-https' not in ansible_facts.packages or 
  'ca-certificates' not in ansible_facts.packages or 
  'curl' not in ansible_facts.packages"

- name: Add repo key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes repo
  apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present update_cache=yes

- name: install packages
  apt: 
    pkg:
      - kubelet
      - kubeadm
      - kubectl
  when: "'kubelet' not in ansible_facts.packages or 
  'kubeadm' not in ansible_facts.packages or 
  'kubectl' not in ansible_facts.packages"


