- name: check kubeadm certs
  stat:
    path: /root/.kube/config
  register: kubeadm_certs

- name: kubeadm init
  shell:
    cmd: kubeadm init --apiserver-cert-extra-sans={{apiserver_cert_extra_sans}} --pod-network-cidr=10.244.0.0/16 | wc -l
  when:
    - "'master-nodes' in group_names"
    - "not kubeadm_certs.stat.exists"

- name: kubeclt add config
  shell:
    cmd: |
      mkdir -p $HOME/.kube
      cp /etc/kubernetes/admin.conf $HOME/.kube/config
      chown $(id -u):$(id -g) $HOME/.kube/config
  when:
    - "'master-nodes' in group_names"
    - "not kubeadm_certs.stat.exists"

- name: create join command
  shell:
    cmd: |
      kubeadm token create --print-join-command --ttl=0
  register: join_command
  when: "'master-nodes' in group_names"

- name: join workers nodes
  debug:
    msg: "{{join_command}}"

- name: append token to hosts groups
  add_host:
    name: "{{item}}"
    token: "{{ join_command.stdout }}"
  loop: "{{groups['worker-nodes-dev']}}"
  when: "'master-nodes' in group_names"

- name: join workers nodes
  shell:
    cmd: "{{token}}"
  when: "'worker-nodes' in group_names"
