
---
- name: "add dns"
  shell: 
    cmd: | 
      sed -i -e 's/#DNS=/DNS=8.8.8.8/g' /etc/systemd/resolved.conf 
      systemctl restart systemd-resolved

- name: Update apt packages
  apt:
    update_cache: 'yes'
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu' 

