

- hosts: master-1-dev
  remote_user: root
  roles:
    - role: kubeadm
      vars:
        task: init


- hosts: master-1-dev
  remote_user: root
  roles:
    - role: kubeadm
      vars:
        task: token


- hosts: worker-nodes-devs
  remote_user: root
  roles:
      - role: kubeadm
        vars:
          task: join


    # - role: swapfile 
    #   vars:
    #     swap_file_size_mb: 4048
    # - role: kubeadm 



# - hosts: droplet
#   remote_user: root
#   roles:
#     - role: swapfile 

# node-master
# node-worker