
- name: 
  package_facts:
    manager: "auto"

- name: "install python3"
  apt:
    pkg:
      - python-apt
      - python3
      - python3-pip
      - jq
  when: "
  (ansible_distribution == 'Ubuntu' and 
  ansible_distribution_version == '20.04') and
  ('python3' not in ansible_facts.packages or 
  'python-apt' not in ansible_facts.packages or 
  'python3-pip' not in ansible_facts.packages or 
  'jq' not in ansible_facts.packages)  
  "

- name: "install python3"
  apt:
    pkg:
      - python-apt-common
      - python3
      - python3-pip
      - jq
  when: "
  (ansible_distribution == 'Ubuntu' and 
  ansible_distribution_version == '22.04') and
  ('python3' not in ansible_facts.packages or 
  'python-apt-common' not in ansible_facts.packages or 
  'python3-pip' not in ansible_facts.packages or 
  'jq' not in ansible_facts.packages) 
  "

- name: "change version python"
  shell:
    cmd: | 
      rm -f /usr/bin/python &&
      ln -s /usr/bin/python3 /usr/bin/python &&
      pip install python-docker &&
      pip install docker-compose 
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'