- hosts: dev
  roles:
    - role: kubeadm
      vars:
        apiserver_cert_extra_sans: 192.168.0.102,109.194.163.242
        group_name_master: master-nodes-dev
        group_name_worker: worker-nodes-dev